# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-nanometrics"
BBFILE_PATTERN_meta-nanometrics = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-nanometrics = "6"

LAYERDEPENDS_meta-nanometrics = "core"
LAYERSERIES_COMPAT_meta-nanometrics = "kirkstone"
